# Generated by Django 4.2.2 on 2023-06-20 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="menu",
            old_name="Inventory",
            new_name="inventory",
        ),
        migrations.RenameField(
            model_name="menu",
            old_name="Price",
            new_name="price",
        ),
        migrations.RenameField(
            model_name="menu",
            old_name="Title",
            new_name="title",
        ),
    ]
